#!/bin/sh

cd "$(dirname "$0")/.."

for i in $(find cyclone/stage0 -type f | grep -o '.*/' | sort -u); do
  echo "cp bazel-bin/$(echo $i | sed -e 's|/stage0/|/|')*.c $i"
  cp bazel-bin/$(echo $i | sed -e 's|/stage0/|/|')*.c $i
done
